version: '{build}'
image: Visual Studio 2017
environment:
  CONFIG_TYPE: Release
  matrix:
  - BUILD_TYPE: Visual Studio 15 2017
    BUILD_PLAY: ON
    QT_FLAVOR: msvc2017 
    ARCH_TYPE: x86_32
    INSTALLER_SCRIPT: installer32.nsi
  - BUILD_TYPE: Visual Studio 15 2017 Win64
    BUILD_PLAY: ON
    INSTALLER_SCRIPT: installer64.nsi
    QT_FLAVOR: msvc2017_64
    ARCH_TYPE: x86_64
  - BUILD_TYPE: Visual Studio 15 2017 Win64
    BUILD_PSFPLAYER: ON
    INSTALLER_SCRIPT: installer64.nsi
  - BUILD_TYPE: Visual Studio 15 2017 Win64
    BUILD_PSFAOT: ON
cache:
  - VulkanSDK.exe -> appveyor.yml
build_script:
- cmd: >-
    set REPO_COMMIT_SHORT=%APPVEYOR_REPO_COMMIT:~0,8%
    
    appveyor SetVariable -Name REPO_COMMIT_SHORT -Value %REPO_COMMIT_SHORT%
    
    git submodule update -q --init --recursive
    
    set VULKAN_VERSION=1.2.131.1
    
    if not exist VulkanSDK.exe curl -L --silent --show-error --output VulkanSDK.exe https://sdk.lunarg.com/sdk/download/%VULKAN_VERSION%/windows/VulkanSDK-%VULKAN_VERSION%-Installer.exe?Human=true
    
    .\VulkanSDK.exe /S
    
    set VULKAN_SDK=C:\VulkanSDK\%VULKAN_VERSION%
    
    call appveyor_build.cmd
    
artifacts:
- path: $(REPO_COMMIT_SHORT)\*.exe
  name: Binaries
- path: $(REPO_COMMIT_SHORT)\play_libretro*.dll
  name: Libretro_Core
deploy:
- provider: S3
  access_key_id: AKIAJGVKEDYESR2BIP7Q
  secret_access_key:
    secure: JFQy5OF0YXW/H6mcQtfxbd4dAJ+m88p5UwOrazZnfHXecN2M08LklayUlaX/51tI
  bucket: playbuilds
  region: us-east-2
  artifact: Binaries
  set_public: true
